[versions]
activityComposeVersion = "1.9.2"
composeBomVersion = "2024.09.03"
composeneumorphism = "1.0.0-alpha02"
composeShimmer = "1.3.1"
datastorePreferences = "1.1.1"
expandablebottombar = "1.5.4"
ezxhelper = "2.2.0"
gson = "2.11.0"
haze = "0.9.0-beta03"
composeBom = "2024.09.03"
datastoreCoreAndroid = "1.1.1"
datastorePreferencesCoreJvm = "1.1.1"
lifecycleRuntimeKtxVersion = "2.8.6"
miuix = "0.2.7"
navigationCompose = "2.8.2"
paletteKtx = "1.0.0"
roomRuntime = "2.6.1"
[libraries]
androidx-activity-compose-v190 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-compose-bom-v20240600 = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-lifecycle-runtime-ktx-v282 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-runtime-ktx = { module = "androidx.navigation:navigation-runtime-ktx", version.ref = "navigationCompose" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "paletteKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
composeneumorphism = { module = "me.nikhilchaudhari:composeNeumorphism", version.ref = "composeneumorphism" }
expandablebottombar = { module = "com.github.st235:expandablebottombar", version.ref = "expandablebottombar" }
ezxhelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezxhelper" }
androidx-datastore-core-android = { group = "androidx.datastore", name = "datastore-core-android", version.ref = "datastoreCoreAndroid" }
androidx-datastore-preferences-core-jvm = { group = "androidx.datastore", name = "datastore-preferences-core-jvm", version.ref = "datastorePreferencesCoreJvm" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
material3 = { module = "androidx.compose.material3:material3" }
miuix = { module = "top.yukonga.miuix.kmp:miuix-android", version.ref = "miuix" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
